# Generated by Django 4.1.2 on 2022-10-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dia_diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dia_diem', models.CharField(max_length=50)),
                ('ten_dia_diem', models.CharField(max_length=100)),
                ('dia_chi_dia_diem', models.TextField()),
            ],
            options={
                'db_table': 'dia_diem',
            },
        ),
        migrations.CreateModel(
            name='kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kho', models.CharField(max_length=50)),
                ('ten_kho', models.CharField(max_length=50)),
                ('so_dien_thoai', models.CharField(max_length=50)),
                ('ma_dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dia_diem')),
            ],
            options={
                'db_table': 'kho',
            },
        ),
        migrations.CreateModel(
            name='loai_hang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_loai_hang', models.CharField(max_length=50)),
                ('ten_loai_hang', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loai_hang',
            },
        ),
        migrations.CreateModel(
            name='nhan_vien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=50)),
                ('ho_ten', models.CharField(max_length=50)),
                ('gioi_tinh', models.CharField(choices=[('0', 'Nam'), ('1', 'Nữ')], max_length=10)),
                ('nam_sinh', models.IntegerField()),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nhan_vien',
            },
        ),
        migrations.CreateModel(
            name='phieu_xuat_hang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu_xuat', models.CharField(max_length=50)),
                ('ngay_lap_phieu_xuat', models.DateField()),
                ('ma_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.kho')),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.nhan_vien')),
            ],
            options={
                'db_table': 'phieu_xuat_hang',
            },
        ),
        migrations.CreateModel(
            name='phieu_nhap_hang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu_nhap', models.CharField(max_length=50)),
                ('ngay_lap_phieu_nhap', models.DateField()),
                ('ma_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.kho')),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.nhan_vien')),
            ],
            options={
                'db_table': 'phieu_nhap_hang',
            },
        ),
        migrations.CreateModel(
            name='mat_hang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mat_hang', models.CharField(max_length=50)),
                ('ten_hang', models.CharField(max_length=150)),
                ('trang_thai', models.CharField(choices=[('1', 'Còn hàng'), ('0', 'Hết hàng')], max_length=10)),
                ('ma_loai_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.loai_hang')),
            ],
            options={
                'db_table': 'mat_hang',
            },
        ),
        migrations.AddField(
            model_name='kho',
            name='ma_loai_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.loai_hang'),
        ),
        migrations.AddField(
            model_name='kho',
            name='ma_nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.nhan_vien'),
        ),
        migrations.AddField(
            model_name='dia_diem',
            name='ma_nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.nhan_vien'),
        ),
        migrations.CreateModel(
            name='chi_tieu_phieu_xuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_xuat', models.FloatField()),
                ('ma_mat_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.mat_hang')),
                ('so_phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.phieu_xuat_hang')),
            ],
            options={
                'db_table': 'chi_tieu_phieu_xuat',
            },
        ),
        migrations.CreateModel(
            name='chi_tiet_phieu_nhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_nhap', models.FloatField()),
                ('ma_mat_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.mat_hang')),
                ('so_phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.phieu_nhap_hang')),
            ],
            options={
                'db_table': 'chi_tiet_phieu_nhap',
            },
        ),
    ]
